package com.situ.aichat.data.local

import androidx.room.Room
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.model.MomentTriggerType
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * T2（真 Room·Robolectric）：R4 交换日记的 DAO 谓词守卫——TA 写的日记（authorCharacterUuid 非 null）
 * 绝不污染「今日自动去重 / 补昨去重」两谓词，且交换查询/解锁门语义正确（契约 §2 F1「谓词守卫」条）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class DiaryDaoExchangeGuardTest {

    private lateinit var db: AppDatabase

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(RuntimeEnvironment.getApplication(), AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
    }

    @After
    fun tearDown() = db.close()

    private fun entry(
        uuid: String,
        ts: Long,
        author: String? = null,
        auto: Boolean = false,
        draft: Boolean = false,
        pet: Boolean = false,
        trigger: String = MomentTriggerType.AUTO_DRAFT.raw,
    ) = DiaryEntryEntity(
        uuid = uuid, content = "c-$uuid", timestamp = ts,
        isAutoGenerated = auto, isDraft = draft, isPetDiary = pet,
        triggerTypeRaw = trigger,
        authorCharacterUuid = author,
    )

    @Test fun `exchange entry does not satisfy today's auto-dedup`(): Unit = runBlocking {
        val dao = db.diaryDao()
        // TA 的交换日记即便标了 auto 位也不算「今天已给用户自动生成」。
        dao.upsertEntry(entry("ex1", ts = 500, author = "char1", auto = true))
        assertEquals(0, dao.countAutoGeneratedSince(0))
        dao.upsertEntry(entry("user-auto", ts = 600, auto = true))
        assertEquals(1, dao.countAutoGeneratedSince(0))
    }

    @Test fun `exchange entry does not satisfy backfill dedup`(): Unit = runBlocking {
        val dao = db.diaryDao()
        dao.upsertEntry(entry("ex1", ts = 500, author = "char1"))
        assertEquals("昨天只有 TA 的信 ≠ 用户昨天有日记", 0, dao.countInRange(0, 1_000))
        dao.upsertEntry(entry("mine", ts = 700))
        assertEquals(1, dao.countInRange(0, 1_000))
    }

    @Test fun `exchange lookup and publish gate follow the spec`(): Unit = runBlocking {
        val dao = db.diaryDao()
        assertNull(dao.exchangeEntryInRange(0, 1_000))
        // 草稿 / 宠物日记都过不了解锁门。
        dao.upsertEntry(entry("draft", ts = 100, draft = true))
        dao.upsertEntry(entry("petd", ts = 150, pet = true))
        assertEquals(0, dao.countPublishedUserDiariesInRange(0, 1_000))
        // 已发布的用户日记开闸。
        dao.upsertEntry(entry("pub", ts = 200))
        assertEquals(1, dao.countPublishedUserDiariesInRange(0, 1_000))
        // TA 的信落库后可按日取回（幂等取回口径）；跨日窗口取不到。
        dao.upsertEntry(entry("ex1", ts = 300, author = "char1"))
        val found = dao.exchangeEntryInRange(0, 1_000)
        assertNotNull(found)
        assertEquals("char1", found!!.authorCharacterUuid)
        assertNull(dao.exchangeEntryInRange(1_000, 2_000))
        // 交换日记不反向计入解锁门/补昨去重（它不是用户日记）：窗口内用户侧 3 条（草稿+宠物+发布），TA 的信被排除。
        assertEquals(1, dao.countPublishedUserDiariesInRange(0, 1_000))
        assertEquals(3, dao.countInRange(0, 1_000))
    }

    // ---- 双保险：历史「改姓」行（图纸 2026-09-05 日记编辑丢作者根治·§7 T2-4）----

    @Test fun `改姓的信仍算当天已有信`(): Unit = runBlocking {
        val dao = db.diaryDao()
        // E4/E16：作者被编辑保存清空（或老备份恢复丢列）的历史行，triggerTypeRaw 仍是 'exchange' →
        // 幂等取回照样认得它，信封位不再复活、角色不再重复写信。
        dao.upsertEntry(entry("ex-orphan", ts = 300, author = null, trigger = MomentTriggerType.EXCHANGE.raw))
        val found = dao.exchangeEntryInRange(0, 1_000)
        assertNotNull(found)
        assertEquals("ex-orphan", found!!.uuid)
        assertNull("跨日窗口照旧取不到", dao.exchangeEntryInRange(1_000, 2_000))
    }

    @Test fun `改姓的信不顶开解锁门`(): Unit = runBlocking {
        val dao = db.diaryDao()
        // E4/E5：改姓行绝不能自己给自己开解锁门；同窗口内用户自己发布的日记照常开闸（守卫不误伤）。
        dao.upsertEntry(entry("ex-orphan", ts = 300, author = null, trigger = MomentTriggerType.EXCHANGE.raw))
        assertEquals(0, dao.countPublishedUserDiariesInRange(0, 1_000))
        dao.upsertEntry(entry("mine", ts = 400))
        assertEquals(1, dao.countPublishedUserDiariesInRange(0, 1_000))
    }
}
