package com.situ.aichat.seam

import androidx.work.Data
import androidx.work.ExistingWorkPolicy
import androidx.work.ListenableWorker
import androidx.work.WorkerParameters
import androidx.work.workDataOf
import com.situ.aichat.data.local.entity.CharacterEntity
import com.situ.aichat.data.local.entity.ConversationEntity
import com.situ.aichat.data.local.entity.MomentPostEntity
import com.situ.aichat.data.local.entity.OfflineMeetingMemoryEntity
import com.situ.aichat.data.model.ApiFunction
import com.situ.aichat.data.model.AppSettings
import com.situ.aichat.data.remote.llm.ApiConfigValues
import com.situ.aichat.data.repository.ApiConfigRepository
import com.situ.aichat.data.repository.CharacterRepository
import com.situ.aichat.data.repository.ConversationRepository
import com.situ.aichat.data.repository.MomentRepository
import com.situ.aichat.data.repository.OfflineMeetingMemoryRepository
import com.situ.aichat.data.repository.SettingsRepository
import com.situ.aichat.moments.MeetingMomentEchoService
import com.situ.aichat.moments.MomentGenerationService
import com.situ.aichat.offline.MeetingMomentEchoPlanner
import com.situ.aichat.prompt.schedule.CharacterSleepChecker
import com.situ.aichat.work.BackgroundScheduler
import com.situ.aichat.work.MeetingMomentEchoWorker
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import io.mockk.unmockkAll
import io.mockk.verify
import java.time.LocalDateTime
import java.time.ZoneId
import kotlin.random.Random
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * T2-K4（卷二 §5④·图纸 §3.3/§7）：**朋友圈呼应帖八道守卫序 + worker 自链**行为测试。
 *
 * 断言从图纸 §3.3 守卫表独立反推：①发帖开关 ②幂等 uuid ③又在见面 ④深夜顺延（不计次数）
 * ⑤睡眠 ⑥摘要未熟/材料尽失 ⑦无 key（且**不**置 MomentApiMissingFlag）⑧角色缺失/内容不合格。
 * Robolectric 只为构造 [MeetingMomentEchoWorker]（CoroutineWorker 需真 Context）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class MeetingMomentEchoServiceTest {

    private val zone: ZoneId = ZoneId.of("Asia/Shanghai")
    /** 2026-08-27 15:00（上海）——不是深夜。 */
    private val now = LocalDateTime.of(2026, 8, 27, 15, 0).atZone(zone).toInstant().toEpochMilli()

    private lateinit var settingsRepo: SettingsRepository
    private lateinit var momentRepo: MomentRepository
    private lateinit var conversationRepo: ConversationRepository
    private lateinit var characterRepo: CharacterRepository
    private lateinit var apiConfigRepo: ApiConfigRepository
    private lateinit var memoryRepo: OfflineMeetingMemoryRepository
    private lateinit var sleepChecker: CharacterSleepChecker
    private lateinit var generationService: MomentGenerationService

    private val character = CharacterEntity(uuid = "char", name = "小雨", creationDate = 0L)
    private val echoUuid = MeetingMomentEchoPlanner.echoPostUuid("sess")

    private fun row(source: String = "llm") = OfflineMeetingMemoryEntity(
        uuid = "r1", characterUuid = "char", conversationUuid = "conv", sessionId = "sess",
        startedAtMillis = now - 5 * 3600_000L, endedAtMillis = now - 4 * 3600_000L,
        location = "咖啡馆", summary = "一起喝了咖啡", sourceRaw = source,
        createdAtMillis = 0L, updatedAtMillis = 0L,
    )

    private fun post() = MomentPostEntity(
        uuid = echoUuid, content = "风很软", timestamp = now, authorTypeRaw = "character",
        characterUuid = "char", isAutoGenerated = true, triggerTypeRaw = "auto_draft",
    )

    @Before
    fun setUp() {
        settingsRepo = mockk(relaxed = true)
        momentRepo = mockk(relaxed = true)
        conversationRepo = mockk(relaxed = true)
        characterRepo = mockk(relaxed = true)
        apiConfigRepo = mockk(relaxed = true)
        memoryRepo = mockk(relaxed = true)
        sleepChecker = mockk(relaxed = true)
        generationService = mockk(relaxed = true)

        // 默认 = 全守卫通过的正常路径（各用例按需覆盖）。
        coEvery { settingsRepo.getAppSettings() } returns AppSettings(momentAutoPostFrequency = 2)
        coEvery { momentRepo.getPost(any()) } returns null
        coEvery { conversationRepo.get("conv") } returns
            ConversationEntity(uuid = "conv", title = "t", characterUuid = "char", creationDate = 0L)
        coEvery { sleepChecker.isSleeping(any(), any(), any(), any()) } returns false
        coEvery { memoryRepo.bySessionId("sess") } returns row()
        coEvery { apiConfigRepo.resolveConfigValues(ApiFunction.MOMENT_GENERATION) } returns
            mockk<ApiConfigValues>(relaxed = true)
        coEvery { characterRepo.get("char") } returns character
        coEvery { generationService.generateEchoPost(any(), any(), any(), any(), any()) } returns post()
    }

    @After fun tearDown() = unmockkAll()

    private fun service(random: Random = Random(7)) = MeetingMomentEchoService(
        settingsRepo, momentRepo, conversationRepo, characterRepo, apiConfigRepo,
        memoryRepo, sleepChecker, generationService, random,
    )

    private fun run(acceptInstantRow: Boolean = false, at: Long = now) = runBlocking {
        service().maybePost("conv", "char", "sess", acceptInstantRow, at, zone)
    }

    // ══════ 守卫序 ══════

    /** 全过 → 发帖。 */
    @Test fun 全守卫通过_发帖() {
        assertEquals(MeetingMomentEchoService.EchoOutcome.Posted, run())
        coVerify(exactly = 1) { generationService.generateEchoPost(character, any(), any(), eq(now), eq(zone)) }
    }

    /** E11 ①：用户把角色发帖频率设为 0 → DROP 静默（呼应不另立门户）。 */
    @Test fun e11_发帖频率为零_drop() {
        coEvery { settingsRepo.getAppSettings() } returns AppSettings(momentAutoPostFrequency = 0)
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())
        coVerify(exactly = 0) { momentRepo.getPost(any()) } // 守卫①在幂等查询之前短路
        coVerify(exactly = 0) { generationService.generateEchoPost(any(), any(), any(), any(), any()) }
    }

    /** E10 ②：这场见面已经有呼应帖（重投/重装恢复）→ DROP，恒至多一条。 */
    @Test fun e10_已存在同uuid帖_drop() {
        coEvery { momentRepo.getPost(echoUuid) } returns post()
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())
        coVerify(exactly = 0) { generationService.generateEchoPost(any(), any(), any(), any(), any()) }
    }

    /** ③ 会话不存在 → DROP（没有会话就没有这场见面）。 */
    @Test fun 会话不存在_drop() {
        coEvery { conversationRepo.get("conv") } returns null
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())
    }

    /** E8 ③：又在见面中 → DEFER（人到齐了不发圈）。 */
    @Test fun e8_又在见面中_defer() {
        coEvery { conversationRepo.get("conv") } returns ConversationEntity(
            uuid = "conv", title = "t", characterUuid = "char", creationDate = 0L,
            isInOfflineMode = true, currentOfflineSessionId = "sess-2",
        )
        assertEquals(MeetingMomentEchoService.EchoOutcome.Defer, run())
        coVerify(exactly = 0) { generationService.generateEchoPost(any(), any(), any(), any(), any()) }
    }

    /** E8 ④：深夜 → DEFER_LATE_NIGHT，顺延分钟数落在次日 09:00–11:30。 */
    @Test fun e8_深夜_顺延到次日上午() {
        val lateNight = LocalDateTime.of(2026, 8, 27, 23, 45).atZone(zone).toInstant().toEpochMilli()
        val outcome = run(at = lateNight)
        assertTrue("应顺延而非直接发：$outcome", outcome is MeetingMomentEchoService.EchoOutcome.DeferLateNight)
        val minutes = (outcome as MeetingMomentEchoService.EchoOutcome.DeferLateNight).minutes
        val landing = java.time.Instant.ofEpochMilli(lateNight).atZone(zone).plusMinutes(minutes)
        assertTrue("落点 $landing 应在 09:00–11:30", landing.hour * 60 + landing.minute in 540..690)
        assertEquals(28, landing.dayOfMonth) // 次日
        coVerify(exactly = 0) { generationService.generateEchoPost(any(), any(), any(), any(), any()) }
    }

    /** ④ 在 ⑤ 之前：深夜时压根不问睡没睡（顺延本就是时刻修正）。 */
    @Test fun 深夜守卫在睡眠守卫之前() {
        val lateNight = LocalDateTime.of(2026, 8, 28, 3, 0).atZone(zone).toInstant().toEpochMilli()
        run(at = lateNight)
        coVerify(exactly = 0) { sleepChecker.isSleeping(any(), any(), any(), any()) }
    }

    /** E8 ⑤：角色在睡 → DEFER（睡着不发圈）。 */
    @Test fun e8_角色在睡_defer() {
        coEvery { sleepChecker.isSleeping("char", any(), any(), any()) } returns true
        assertEquals(MeetingMomentEchoService.EchoOutcome.Defer, run())
    }

    /** ⑥ 摘要还是即时要点 → DEFER（等它熟）。 */
    @Test fun 摘要未熟_defer() {
        coEvery { memoryRepo.bySessionId("sess") } returns row(source = "instant")
        assertEquals(MeetingMomentEchoService.EchoOutcome.Defer, run())
        coVerify(exactly = 0) { generationService.generateEchoPost(any(), any(), any(), any(), any()) }
    }

    /** ⑥ 兜底档：即时要点也认，照发。 */
    @Test fun 兜底档_即时要点也发() {
        coEvery { memoryRepo.bySessionId("sess") } returns row(source = "instant")
        assertEquals(MeetingMomentEchoService.EchoOutcome.Posted, run(acceptInstantRow = true))
    }

    /** ⑥ 无行 → DEFER；兜底档仍无行 → DROP（材料尽失）。 */
    @Test fun 无行_先等后放弃() {
        coEvery { memoryRepo.bySessionId("sess") } returns null
        assertEquals(MeetingMomentEchoService.EchoOutcome.Defer, run())
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run(acceptInstantRow = true))
    }

    /** E12 ⑦：无 key → DROP 静默，且**不**置 MomentApiMissingFlag（那是节奏批路的诊断旗）。 */
    @Test fun e12_无key_drop且不置诊断旗() {
        com.situ.aichat.moments.MomentApiMissingFlag.set(RuntimeEnvironment.getApplication(), false)
        coEvery { apiConfigRepo.resolveConfigValues(ApiFunction.MOMENT_GENERATION) } returns null

        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())

        assertEquals(
            false,
            com.situ.aichat.moments.MomentApiMissingFlag.get(RuntimeEnvironment.getApplication()),
        )
    }

    /** ⑧ 角色已删 → DROP。 */
    @Test fun 角色已删_drop() {
        coEvery { characterRepo.get("char") } returns null
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())
    }

    /** ⑧ 内容两次不合格（J9）→ DROP 静默放弃。 */
    @Test fun 内容不合格_drop() {
        coEvery { generationService.generateEchoPost(any(), any(), any(), any(), any()) } returns null
        assertEquals(MeetingMomentEchoService.EchoOutcome.Drop, run())
    }

    // ══════ worker 自链 ══════

    private fun worker(serviceMock: MeetingMomentEchoService, scheduler: BackgroundScheduler, deferCount: Int?) =
        MeetingMomentEchoWorker(
            appContext = RuntimeEnvironment.getApplication(),
            params = mockk<WorkerParameters>(relaxed = true).also { params ->
                val base = mutableListOf<Pair<String, Any>>(
                    MeetingMomentEchoWorker.KEY_CONVERSATION_UUID to "conv",
                    MeetingMomentEchoWorker.KEY_CHARACTER_UUID to "char",
                    MeetingMomentEchoWorker.KEY_SESSION_ID to "sess",
                )
                if (deferCount != null) base.add(MeetingMomentEchoWorker.KEY_DEFER_COUNT to deferCount)
                every { params.inputData } returns workDataOf(*base.toTypedArray())
            },
            service = serviceMock,
            backgroundScheduler = scheduler,
        )

    private fun stubOutcome(outcome: MeetingMomentEchoService.EchoOutcome): MeetingMomentEchoService {
        val m = mockk<MeetingMomentEchoService>(relaxed = true)
        coEvery { m.maybePost(any(), any(), any(), any(), any(), any()) } returns outcome
        return m
    }

    /** DEFER → 30 分钟 REPLACE 重排，次数 +1。 */
    @Test fun worker_defer_三十分钟重排且计次() = runBlocking {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        val data = slot<Data>()

        val result = worker(stubOutcome(MeetingMomentEchoService.EchoOutcome.Defer), scheduler, null).doWork()

        assertTrue(result is ListenableWorker.Result.Success)
        verify(exactly = 1) {
            scheduler.scheduleOneShot(
                uniqueName = eq("meeting_moment_echo_sess"),
                workerClass = eq(MeetingMomentEchoWorker::class.java),
                initialDelay = eq(java.time.Duration.ofMinutes(30L)),
                requireNetwork = eq(true),
                existingPolicy = eq(ExistingWorkPolicy.REPLACE),
                inputData = capture(data),
            )
        }
        assertEquals(1, data.captured.getInt(MeetingMomentEchoWorker.KEY_DEFER_COUNT, -1))
    }

    /** 深夜顺延 → 按给定分钟数重排，且**不**计次数（deferCount 原样带走）。 */
    @Test fun worker_深夜顺延_不计次数() = runBlocking {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        val data = slot<Data>()
        val svc = stubOutcome(MeetingMomentEchoService.EchoOutcome.DeferLateNight(570L))

        worker(svc, scheduler, deferCount = 3).doWork()

        verify(exactly = 1) {
            scheduler.scheduleOneShot<MeetingMomentEchoWorker>(
                any(), any(), eq(java.time.Duration.ofMinutes(570L)), any(), eq(ExistingWorkPolicy.REPLACE), capture(data),
            )
        }
        assertEquals("深夜是时刻修正，不占延后次数", 3, data.captured.getInt(MeetingMomentEchoWorker.KEY_DEFER_COUNT, -1))
    }

    /** 延后到顶（6 次）→ 不再排，改带 acceptInstantRow=true 再试一次。 */
    @Test fun worker_到顶_走兜底档且停链() = runBlocking {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        val svc = stubOutcome(MeetingMomentEchoService.EchoOutcome.Defer)

        worker(svc, scheduler, deferCount = 6).doWork()

        verify(exactly = 0) { scheduler.scheduleOneShot<MeetingMomentEchoWorker>(any(), any(), any(), any(), any(), any()) }
        coVerify(exactly = 1) { svc.maybePost("conv", "char", "sess", true, any(), any()) }
    }

    /** POSTED / DROP → 绝不自链。 */
    @Test fun worker_发了或放弃_零自链() = runBlocking {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        worker(stubOutcome(MeetingMomentEchoService.EchoOutcome.Posted), scheduler, 0).doWork()
        worker(stubOutcome(MeetingMomentEchoService.EchoOutcome.Drop), scheduler, 0).doWork()
        verify(exactly = 0) { scheduler.scheduleOneShot<MeetingMomentEchoWorker>(any(), any(), any(), any(), any(), any()) }
    }

    /**
     * 首排（见面结束掷点中签后）：唯一任务名 + KEEP（同 session 不重排）+ 首延 ∈[180,420] 分钟 +
     * deferCount 归零。掷点本身在 [MeetingMomentEchoPlanner.shouldPost]（T1-K3 已钉 74/75 边界）。
     */
    @Test fun worker_首排_KEEP且首延三到七小时() {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        val delay = slot<java.time.Duration>()
        val data = slot<Data>()

        MeetingMomentEchoWorker.scheduleFirst(scheduler, "conv", "char", "sess")

        verify(exactly = 1) {
            scheduler.scheduleOneShot(
                uniqueName = eq("meeting_moment_echo_sess"),
                workerClass = eq(MeetingMomentEchoWorker::class.java),
                initialDelay = capture(delay),
                requireNetwork = eq(true),
                existingPolicy = eq(ExistingWorkPolicy.KEEP), // 首排 KEEP：自链才用 REPLACE
                inputData = capture(data),
            )
        }
        assertTrue("首延 ${delay.captured} 应 ∈[180,420] 分钟", delay.captured.toMinutes() in 180L..420L)
        assertEquals(0, data.captured.getInt(MeetingMomentEchoWorker.KEY_DEFER_COUNT, -1))
        assertEquals("conv", data.captured.getString(MeetingMomentEchoWorker.KEY_CONVERSATION_UUID))
        assertEquals("char", data.captured.getString(MeetingMomentEchoWorker.KEY_CHARACTER_UUID))
        assertEquals("sess", data.captured.getString(MeetingMomentEchoWorker.KEY_SESSION_ID))
    }

    /** 服务抛异常 → 吞掉、恒 success、不自链。 */
    @Test fun worker_异常_吞掉且零自链() = runBlocking {
        val scheduler = mockk<BackgroundScheduler>(relaxed = true)
        val svc = mockk<MeetingMomentEchoService>(relaxed = true)
        coEvery { svc.maybePost(any(), any(), any(), any(), any(), any()) } throws IllegalStateException("炸了")

        val result = worker(svc, scheduler, 0).doWork()

        assertTrue(result is ListenableWorker.Result.Success)
        verify(exactly = 0) { scheduler.scheduleOneShot<MeetingMomentEchoWorker>(any(), any(), any(), any(), any(), any()) }
    }
}
