package com.situ.aichat.prompt.diary

import android.util.Log
import com.situ.aichat.data.local.dao.CharacterDao
import com.situ.aichat.data.local.dao.MessageDao
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.model.AppSettings
import com.situ.aichat.data.model.DiaryVisibility
import com.situ.aichat.data.model.MomentTriggerType
import com.situ.aichat.data.repository.DiaryRepository
import com.situ.aichat.data.repository.SettingsRepository
import com.situ.aichat.gift.GiftMomentQueueService
import com.situ.aichat.pet.PetShopMomentQueueService
import com.situ.aichat.prompt.schedule.CharacterSleepChecker
import com.situ.aichat.util.DateFormatters
import kotlinx.coroutines.sync.Mutex
import java.time.Instant
import java.time.ZoneId
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * 日记自动生成编排（M07 7.1.2）。1:1 对齐 iOS `BackgroundTaskRunner.runDiaryGeneration`（先补昨天、再查今天）
 * + `DiaryGenerationActor.checkAndAutoGenerate` 的判定门。被 [com.situ.aichat.work.DiaryGenerationWorker]
 * （回前台 + 每日兜底）调用。
 *
 * 门控顺序（今日）：系统并发锁 → diaryAutoGenerateEnabled → 沉浸模式(P10 stub=false) → 时间门槛(now≥设定) →
 * 今日去重(排宠物日记) → 全员睡觉跳过 → 生成落库（isAutoGenerated/isDraft/openToAI，timestamp=now）。
 *
 * 纯时间判定（[parseHourMinute] / [targetTimeMillis] / [backfillTimestampMillis]）放 companion 便于单测。
 */
@Singleton
class DiaryGenerationCoordinator @Inject constructor(
    private val diaryRepository: DiaryRepository,
    private val characterDao: CharacterDao,
    private val messageDao: MessageDao,
    private val settingsRepo: SettingsRepository,
    private val sleepChecker: CharacterSleepChecker,
    private val service: DiaryGenerationService,
    private val giftQueue: GiftMomentQueueService,
    private val petShopQueue: PetShopMomentQueueService,
    private val commentService: DiaryCommentService,
    private val monthlyReviewService: MonthlyReviewService,
) {
    private val generationMutex = Mutex()

    /** 先补昨天，再查今天（1:1 iOS runDiaryGeneration）；跨月后顺带兜底上月回顾（R5·开关内自查）。 */
    suspend fun runDiaryGeneration() {
        backfillYesterday()
        checkAndAutoGenerateToday()
        monthlyReviewService.checkAndGenerateLastMonth()
    }

    /** 今日自动生成（含全部判定门）。被 worker 调用，自带并发串行化。 */
    suspend fun checkAndAutoGenerateToday() {
        if (!generationMutex.tryLock()) {
            Log.d(TAG, "日记生成进行中，跳过本次触发")
            return
        }
        try {
            val settings = settingsRepo.getAppSettings()
            if (!settings.diaryAutoGenerateEnabled) return

            val now = System.currentTimeMillis()
            val zone = ZoneId.systemDefault()
            val hm = parseHourMinute(settings.diaryAutoGenerateTime) ?: return
            if (now < targetTimeMillis(now, hm.first, hm.second, zone)) return

            val startOfDay = DateFormatters.startOfDayMillis(now, zone)
            if (diaryRepository.hasAutoGeneratedToday(startOfDay)) return

            // 全员睡觉时跳过（下次 worker 重试）。
            val characters = characterDao.getAll()
            if (characters.isNotEmpty() &&
                characters.all { sleepChecker.isSleeping(it.uuid, settings.scheduleSystemEnabled, now, zone) }
            ) {
                Log.d(TAG, "全员睡觉，跳过自动日记")
                return
            }

            // 礼物分支（P9.2e）→ 宠物商店分支（P9.3c，gift 未命中才试）。1:1 iOS：inspiration=gift?:petShop，
            // triggerType 礼物>宠物商店>auto_draft。礼物中文/英文 hint 见各 Service；宠物商店日记 hint 为中文。
            val giftBranch = giftQueue.resolveGiftBranchForDiary(now)
            val petShopBranch = if (giftBranch == null) petShopQueue.resolveDiaryBranch(now) else null
            val inspiration = giftBranch?.promptHint ?: petShopBranch?.promptHint
            val draft = service.generateDraft(now, zone, giftInspiration = inspiration) ?: return
            persistAutoEntry(draft, now, giftBranch, petShopBranch != null, settings)
            Log.d(TAG, "自动日记已生成")
        } finally {
            generationMutex.unlock()
        }
    }

    /**
     * 补昨天（1:1 iOS backfillYesterdayDiary）：开关开 + 昨天无任何日记(手写/自动都算) + 昨天有聊天记录 →
     * 生成并落库，timestamp = 昨天 0 点 + 22h（让它落在昨天日期）。无并发锁（对齐 iOS；今日检查持锁兜底）。
     */
    suspend fun backfillYesterday() {
        val settings = settingsRepo.getAppSettings()
        if (!settings.diaryAutoGenerateEnabled) return

        val zone = ZoneId.systemDefault()
        val todayStart = DateFormatters.startOfDayMillis(System.currentTimeMillis(), zone)
        val yesterdayStart = Instant.ofEpochMilli(todayStart).atZone(zone).minusDays(1)
            .toInstant().toEpochMilli()

        if (diaryRepository.hasAnyEntryInRange(yesterdayStart, todayStart)) return
        // 昨天必须有聊天记录才补（取 1 条判定即可）。
        if (messageDao.messagesInRange(yesterdayStart, todayStart, 1).isEmpty()) return

        // 礼物分支用「昨天 22:00」作 now 锚定 48h 窗口（前天晚 → 昨天晚，避免把今日礼物带进昨日日记），1:1 iOS
        // backfillNow；同一时间戳也作为补写日记的 timestamp（让它落在昨天日期）。
        val backfillTs = backfillTimestampMillis(yesterdayStart)
        val giftBranch = giftQueue.resolveGiftBranchForDiary(backfillTs)
        val petShopBranch = if (giftBranch == null) petShopQueue.resolveDiaryBranch(backfillTs) else null
        val inspiration = giftBranch?.promptHint ?: petShopBranch?.promptHint
        val draft = service.generateDraft(yesterdayStart, zone, giftInspiration = inspiration) ?: return
        persistAutoEntry(draft, backfillTs, giftBranch, petShopBranch != null, settings)
        Log.d(TAG, "昨日日记已补生成")
    }

    /**
     * 手动「AI 帮我写」（7.1.5 撰写页用）：仅返回草稿（正文+推断心情），由 UI 决定是否落库。
     * **不走礼物分支**（1:1 iOS：礼物分支仅自动今日/补昨日两条自动路径注入，手动撰写不注入 giftInspiration）。
     * @param moodHint 用户已手选的心情（"😊 开心" 式）→ 进 prompt 心情段（R2 F2）。
     * @param guide 三问引导答案（U2①·撰写页 sheet·全空/ null = 不注入引导段）。
     */
    suspend fun generateDraftForComposer(
        dateMillis: Long,
        moodHint: String? = null,
        guide: DiaryGuideAnswers? = null,
        /** 撰写页里已贴好的照片张数（§B8）：让 AI 至少知道「有 N 张照片但看不到」，别写出与照片脱节的正文。 */
        photoCount: Int = 0,
    ): DiaryDraft? = service.generateDraft(
        dateMillis = dateMillis,
        zone = ZoneId.systemDefault(),
        giftInspiration = null,
        moodHint = moodHint,
        guide = guide,
        photoCount = photoCount,
    )

    /**
     * 落自动日记 + R3「自动直发」：`diaryAutoPublishEnabled` 开 → isDraft=false 直接发布并走既有评论调度
     * （自动日记恒 openToAI；worker 执行时还会再验可见性/评论开关，删除日记会取消任务）；关（默认）→ 草稿，
     * 保留用户先润色的权利（O3 锁定）。今日/补昨两路共用。
     */
    private suspend fun persistAutoEntry(
        draft: DiaryDraft,
        timestamp: Long,
        giftBranch: GiftMomentQueueService.GiftBranchResult?,
        isPetShopPurchase: Boolean,
        settings: AppSettings,
    ) {
        val autoPublish = settings.diaryAutoPublishEnabled
        val entry = autoEntry(draft, timestamp, giftBranch, isPetShopPurchase, isDraft = !autoPublish)
        diaryRepository.upsert(entry)
        if (autoPublish) commentService.scheduleComments(entry.uuid, settings.diaryCommentDelay)
    }

    /**
     * 落自动日记。triggerType：礼物分支命中 → gift_received（+relatedGiftId=代表礼物）；否则宠物商店分支命中 →
     * pet_shop_purchase（relatedGiftId=null，代表物品**不**入库，1:1 iOS）；都没 → auto_draft。
     * R2：带推断心情落库（moodText 留 null——标签是 UI 层资源事务，emoji 已足够驱动色带/日历/洇染）。
     */
    private fun autoEntry(
        draft: DiaryDraft,
        timestamp: Long,
        giftBranch: GiftMomentQueueService.GiftBranchResult? = null,
        isPetShopPurchase: Boolean = false,
        isDraft: Boolean = true,
    ): DiaryEntryEntity =
        DiaryEntryEntity(
            uuid = UUID.randomUUID().toString(),
            content = draft.content,
            timestamp = timestamp,
            moodEmoji = draft.moodEmoji,
            isAutoGenerated = true,
            isDraft = isDraft,
            visibilityRaw = DiaryVisibility.OPEN_TO_AI.raw,
            triggerTypeRaw = when {
                giftBranch != null -> MomentTriggerType.GIFT_RECEIVED
                isPetShopPurchase -> MomentTriggerType.PET_SHOP_PURCHASE
                else -> MomentTriggerType.AUTO_DRAFT
            }.raw,
            relatedGiftId = giftBranch?.representativeGiftId,
        )

    companion object {
        private const val TAG = "DiaryCoord"
        private const val BACKFILL_HOUR_OFFSET_MILLIS = 22L * 60 * 60 * 1000

        /** 解析 "HH:mm"（对齐 iOS split(":")+两段；越界小时/分钟视为无效 → null，等价 iOS guard）。 */
        internal fun parseHourMinute(s: String): Pair<Int, Int>? {
            val parts = s.split(":").map { it.trim() }
            if (parts.size != 2) return null
            val h = parts[0].toIntOrNull() ?: return null
            val m = parts[1].toIntOrNull() ?: return null
            if (h !in 0..23 || m !in 0..59) return null
            return h to m
        }

        /** 今天的 [hour]:[minute] 时刻（epoch 毫秒）。对齐 iOS calendar.date(bySettingHour:...)。 */
        internal fun targetTimeMillis(nowMillis: Long, hour: Int, minute: Int, zone: ZoneId): Long =
            Instant.ofEpochMilli(nowMillis).atZone(zone).toLocalDate()
                .atTime(hour, minute).atZone(zone).toInstant().toEpochMilli()

        /** 补昨天的日记时间戳 = 昨天 0 点 + 22h（对齐 iOS backfillNow）。 */
        internal fun backfillTimestampMillis(yesterdayStartMillis: Long): Long =
            yesterdayStartMillis + BACKFILL_HOUR_OFFSET_MILLIS
    }
}
