package com.situ.aichat.pet

import android.util.Log
import com.situ.aichat.data.local.dao.UserProfileDao
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.model.ApiFunction
import com.situ.aichat.data.model.DiaryVisibility
import com.situ.aichat.data.remote.llm.ChatMessageDto
import com.situ.aichat.diagnostics.ContextLogService
import com.situ.aichat.diagnostics.LogSource
import com.situ.aichat.data.repository.ApiConfigRepository
import com.situ.aichat.data.repository.DiaryRepository
import com.situ.aichat.data.repository.PetRepository
import com.situ.aichat.data.repository.SettingsRepository
import com.situ.aichat.prompt.GeneratedContentValidator
import com.situ.aichat.prompt.memory.MemoryService
import com.situ.aichat.util.DateFormatters
import java.time.ZoneId
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * 宠物日记自动生成（1:1 iOS `PetDiaryGenerationService.checkAndAutoGenerate`）。每天生成一篇**宠物视角**
 * 的日记（第一人称），复用 [DiaryEntryEntity]（isPetDiary=true）+ 日记生成的 API 路由（[ApiFunction.DIARY_GENERATION]）。
 * App 回前台时由 [com.situ.aichat.ui.AppViewModel] 调用（见启动批量衰减接线）。
 *
 * 门控（1:1 iOS）：petSystemEnabled && petDiaryAutoGenerateEnabled（默认 **false**）&& 非沉浸（P10 stub）&&
 * 今日无宠物日记 && 有 API → 取第一只宠物 → buildPetDiaryPrompt → completion(temp 0.85) → 剥 think →
 * [GeneratedContentValidator] 脏数据门 → 存 DiaryEntry(isPetDiary/petSpeciesRaw/moodEmoji)。
 */
@Singleton
class PetDiaryGenerationService @Inject constructor(
    private val settingsRepo: SettingsRepository,
    private val petRepository: PetRepository,
    private val diaryRepository: DiaryRepository,
    private val apiConfigRepo: ApiConfigRepository,
    private val contextLog: ContextLogService,
    private val userProfileDao: UserProfileDao,
) {
    suspend fun checkAndAutoGenerate(
        now: Long = System.currentTimeMillis(),
        zone: ZoneId = ZoneId.systemDefault(),
    ) {
        val settings = settingsRepo.getAppSettings()
        if (!settings.petSystemEnabled) return
        if (!settings.petDiaryAutoGenerateEnabled) return

        // 今日是否已有宠物日记
        val startOfDay = DateFormatters.startOfDayMillis(now, zone)
        if (diaryRepository.hasPetDiaryToday(startOfDay)) return

        // 取第一只宠物（iOS fetchLimit 1）
        val pet = petRepository.getAll().firstOrNull() ?: return

        // API 配置（复用日记生成路由）
        val config = apiConfigRepo.resolveConfigValues(ApiFunction.DIARY_GENERATION)
        if (config == null) {
            Log.d(TAG, "宠物日记跳过：未配置 API")
            return
        }

        val ownerName = userProfileDao.get()?.nickname?.trim()?.takeIf { it.isNotEmpty() } ?: OWNER_FALLBACK
        val prompt = PetDiaryPrompts.buildPetDiaryPrompt(pet, ownerName)
        val messages = listOf(
            ChatMessageDto(role = "system", content = prompt),
            ChatMessageDto(role = "user", content = "请以宠物的视角写今天的日记。"),
        )

        val content = try {
            // iOS 不剥 think；安卓沿用日记路径剥 <think>（DeepSeek 推理模型会漏标签），再判非空。
            MemoryService.strippingThinkingTags(
                contextLog.completion(
                    source = LogSource.PET_DIARY,
                    characterName = pet.name,
                    config = config,
                    messages = messages,
                    temperature = 0.85,
                ),
            )
        } catch (e: Exception) {
            Log.e(TAG, "宠物日记生成失败: ${e.message}")
            return
        }
        if (content.isBlank()) return
        // 脏数据门（与日记 / 朋友圈 / 评论等内容类同一道闸）：服务商偶发把「Token count: 2937」「{"error": …}」这类
        // 调试串当正文返回，不拦就会被存成当天的宠物日记，且今天不会再生成。日志只记原因，不打正文。
        if (!GeneratedContentValidator.isLikelyValid(content)) {
            Log.w(TAG, "宠物日记丢弃（${pet.name}）：${GeneratedContentValidator.describeInvalidReason(content)}")
            return
        }

        diaryRepository.upsert(
            DiaryEntryEntity(
                uuid = UUID.randomUUID().toString(),
                content = content,
                timestamp = now,
                moodEmoji = PetDiaryPrompts.petMoodEmoji(pet),
                isAutoGenerated = true,
                isDraft = false, // 宠物日记直接发布（openToAI），非草稿（对齐 iOS）
                isPetDiary = true,
                petSpeciesRaw = pet.speciesRaw,
                visibilityRaw = DiaryVisibility.OPEN_TO_AI.raw,
            ),
        )
        Log.d(TAG, "宠物日记已生成（${pet.name}）")
    }

    private companion object {
        const val TAG = "PetDiaryGen"
        const val OWNER_FALLBACK = "主人"
    }
}
