package com.situ.aichat.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import com.situ.aichat.data.local.entity.DiaryCommentEntity
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.local.entity.DiaryEntryWithComments
import com.situ.aichat.data.local.entity.DiaryReactionEntity
import com.situ.aichat.data.local.entity.MonthlyReviewEntity
import kotlinx.coroutines.flow.Flow

/**
 * Diary read/write (M07). Comments are sorted ascending by timestamp (iOS `DiaryDetailView`).
 * The reactive `observe*` queries auto-refresh when a background-generated entry lands — improving
 * on iOS's manual `onAppear` refetch.
 */
@Dao
interface DiaryDao {

    // ---- Reads: lists & detail (with comments, one shot) ----

    @Transaction
    @Query("SELECT * FROM diary_entries ORDER BY timestamp DESC")
    fun observeAllWithComments(): Flow<List<DiaryEntryWithComments>>

    @Transaction
    @Query("SELECT * FROM diary_entries WHERE timestamp >= :start AND timestamp < :end ORDER BY timestamp DESC")
    suspend fun entriesInRangeWithComments(start: Long, end: Long): List<DiaryEntryWithComments>

    @Transaction
    @Query("SELECT * FROM diary_entries WHERE uuid = :uuid LIMIT 1")
    suspend fun getEntryWithComments(uuid: String): DiaryEntryWithComments?

    /** 单条日记（含评论）的响应式观察——详情页用，异步落地的 AI 评论会自动刷新到打开的详情。 */
    @Transaction
    @Query("SELECT * FROM diary_entries WHERE uuid = :uuid LIMIT 1")
    fun observeEntryWithComments(uuid: String): Flow<DiaryEntryWithComments?>

    @Query("SELECT * FROM diary_entries WHERE uuid = :uuid LIMIT 1")
    suspend fun getEntry(uuid: String): DiaryEntryEntity?

    /** 全部日记正文（按时间升序），供备份导出（13.6 超越 iOS：iOS 只备评论不备正文）。 */
    @Query("SELECT * FROM diary_entries ORDER BY timestamp ASC")
    suspend fun getAllEntries(): List<DiaryEntryEntity>

    /** Plain entries in a range (no comments) — calendar dots only need timestamps. */
    @Query("SELECT * FROM diary_entries WHERE timestamp >= :start AND timestamp < :end ORDER BY timestamp DESC")
    suspend fun entriesInRange(start: Long, end: Long): List<DiaryEntryEntity>

    // ---- Generation-support counts (M07 7.1.2) ----

    /**
     * Today's auto-generation dedup. iOS has a Service-vs-Actor mismatch here; the Android port
     * deliberately adopts the Service predicate `isAutoGenerated && !isPetDiary` (the correct intent:
     * pet diaries have their own daily check, so a pet diary today must not suppress the normal one).
     * R4：补 `authorCharacterUuid IS NULL` 守卫——TA 的交换日记绝不抵今天「给用户」的自动日记。
     */
    @Query(
        "SELECT COUNT(*) FROM diary_entries WHERE timestamp >= :startOfDay AND isAutoGenerated = 1 " +
            "AND isPetDiary = 0 AND authorCharacterUuid IS NULL",
    )
    suspend fun countAutoGeneratedSince(startOfDay: Long): Int

    /**
     * Yesterday-backfill dedup: ANY entry in range counts (manual + auto), per iOS.
     * R4：补 `authorCharacterUuid IS NULL` 守卫——昨天只有 TA 的交换日记 ≠ 用户昨天有日记，补昨不该被抵。
     */
    @Query("SELECT COUNT(*) FROM diary_entries WHERE timestamp >= :start AND timestamp < :end AND authorCharacterUuid IS NULL")
    suspend fun countInRange(start: Long, end: Long): Int

    // ---- 交换日记（R4） ----

    /**
     * 该日的交换日记（角色写的·每日至多一篇·懒生成幂等取回）。
     * 双保险（2026-09-05）：`triggerTypeRaw='exchange'` 也认——历史上被编辑保存清掉 authorCharacterUuid 的
     * 旧行（含 R6-3② 之前的老备份恢复行）照样算「当天已收到信」，不再让信封位复活、角色重复写信。
     */
    @Query(
        "SELECT * FROM diary_entries WHERE (authorCharacterUuid IS NOT NULL OR triggerTypeRaw = 'exchange') " +
            "AND timestamp >= :start AND timestamp < :end LIMIT 1",
    )
    suspend fun exchangeEntryInRange(start: Long, end: Long): DiaryEntryEntity?

    /**
     * 回流消化候选（记忆改造一期·日记回流·图纸 §3.5-C·最旧优先·上限 2）：某角色的交换日记（已发布·未消化·
     * timestamp ≤ before 留 24h 收用户回应）。用户回应经既有 [commentsForEntry] 取 isFromUser=1 前 2 条。
     */
    @Query(
        "SELECT * FROM diary_entries WHERE authorCharacterUuid = :charUuid AND triggerTypeRaw = 'exchange' " +
            "AND digestedAtMillis IS NULL AND isDraft = 0 AND timestamp <= :before ORDER BY timestamp ASC LIMIT 2",
    )
    suspend fun exchangeDiariesToDigest(charUuid: String, before: Long): List<DiaryEntryEntity>

    /** 回流消化标记（记忆改造一期·图纸 §3.5-C·列级 UPDATE·消化作业成功后写）。 */
    @Query("UPDATE diary_entries SET digestedAtMillis = :now WHERE uuid = :uuid")
    suspend fun markDigested(uuid: String, now: Long)

    /**
     * 交换解锁门：该日用户**已发布**（非草稿·非宠物）的日记数。
     * 双保险（2026-09-05）：排除 `triggerTypeRaw='exchange'`——TA 的信绝不能自己顶开自己的解锁门。
     */
    @Query(
        "SELECT COUNT(*) FROM diary_entries WHERE authorCharacterUuid IS NULL AND triggerTypeRaw <> 'exchange' " +
            "AND isDraft = 0 AND isPetDiary = 0 AND timestamp >= :start AND timestamp < :end",
    )
    suspend fun countPublishedUserDiariesInRange(start: Long, end: Long): Int

    /** Gift-branch dedup: timestamp of the most recent gift-triggered entry (drafts included), per iOS. */
    @Query("SELECT timestamp FROM diary_entries WHERE triggerTypeRaw = 'gift_received' ORDER BY timestamp DESC LIMIT 1")
    suspend fun lastGiftDiaryTimestamp(): Long?

    /** 宠物商店日记分支 dedup（P9.3c）：最近一条 triggerType=pet_shop_purchase 日记时间戳（含草稿）。1:1 iOS `lastPetShopDiaryTime`。 */
    @Query("SELECT timestamp FROM diary_entries WHERE triggerTypeRaw = 'pet_shop_purchase' ORDER BY timestamp DESC LIMIT 1")
    suspend fun lastPetShopDiaryTimestamp(): Long?

    /** Pet-diary daily dedup (P8.2): a pet diary today suppresses the next auto pet diary (iOS predicate). */
    @Query("SELECT COUNT(*) FROM diary_entries WHERE timestamp >= :startOfDay AND isPetDiary = 1")
    suspend fun countPetDiariesSince(startOfDay: Long): Int

    /** 全表日记条数（性能采集规模数 `diaryEntries`·图纸 §3.2·只在 flush 时取一次）。 */
    @Query("SELECT COUNT(*) FROM diary_entries")
    suspend fun countAll(): Int

    // ---- Writes ----

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertEntry(entry: DiaryEntryEntity)

    /** Deletes the entry; comments cascade via FK. */
    @Query("DELETE FROM diary_entries WHERE uuid = :uuid")
    suspend fun deleteEntry(uuid: String)

    // ---- Comments ----

    @Query("SELECT * FROM diary_comments WHERE entryUuid = :entryUuid ORDER BY timestamp ASC")
    suspend fun commentsForEntry(entryUuid: String): List<DiaryCommentEntity>

    /** 全部日记评论（按时间升序），供备份导出（13.6）。 */
    @Query("SELECT * FROM diary_comments ORDER BY timestamp ASC")
    suspend fun getAllComments(): List<DiaryCommentEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertComment(comment: DiaryCommentEntity)

    @Query("DELETE FROM diary_comments WHERE id = :id")
    suspend fun deleteComment(id: String)

    /** Same-character dedup when scheduling AI comments (iOS skips a character that already commented). */
    @Query("SELECT COUNT(*) FROM diary_comments WHERE entryUuid = :entryUuid AND characterUuid = :characterUuid")
    suspend fun commentCountByCharacter(entryUuid: String, characterUuid: String): Int

    /** 删角色时清掉它在所有日记（含他人日记）下的评论（1:1 iOS MomentCleanupService 删 DiaryComment by characterUUID）。 */
    @Query("DELETE FROM diary_comments WHERE characterUuid = :characterUuid")
    suspend fun deleteCommentsByCharacter(characterUuid: String)

    // ---- 月度回顾（R5） ----

    /** 每月一篇（monthStartMillis 唯一 + IGNORE = 幂等·worker 重试安全）。 */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertMonthlyReview(review: MonthlyReviewEntity)

    @Query("SELECT * FROM monthly_reviews WHERE monthStartMillis = :monthStartMillis LIMIT 1")
    suspend fun monthlyReviewFor(monthStartMillis: Long): MonthlyReviewEntity?

    /** 全部月度回顾（响应式·列表月分节头部入口卡用）。 */
    @Query("SELECT * FROM monthly_reviews ORDER BY monthStartMillis DESC")
    fun observeMonthlyReviews(): Flow<List<MonthlyReviewEntity>>

    /** 全部月度回顾（备份导出用·R6-3②）。 */
    @Query("SELECT * FROM monthly_reviews")
    suspend fun getAllMonthlyReviews(): List<MonthlyReviewEntity>

    // ---- Reactions（R3 角色点赞） ----

    /** 同角色同条目唯一索引 + IGNORE = 天然防重（worker 重试安全）。 */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertReaction(reaction: DiaryReactionEntity)

    /** 全部日记点赞（备份导出用·R6-3②）。 */
    @Query("SELECT * FROM diary_reactions")
    suspend fun getAllReactions(): List<DiaryReactionEntity>

    /** 删角色时清掉它的所有日记点赞（对齐 [deleteCommentsByCharacter] 清理口径）。 */
    @Query("DELETE FROM diary_reactions WHERE characterUuid = :characterUuid")
    suspend fun deleteReactionsByCharacter(characterUuid: String)

    /** 我们的日子·卷一·只读：该角色已发布的全部交换日记（timestamp 升序·事实层取当日最早一篇·总图纸 §3.5）。 */
    @Query("SELECT * FROM diary_entries WHERE authorCharacterUuid = :charUuid AND triggerTypeRaw = 'exchange' AND isDraft = 0 ORDER BY timestamp ASC")
    suspend fun exchangeEntriesForCharacter(charUuid: String): List<DiaryEntryEntity>
}
